### ISSUE TITLE
Cant play/pause Music (iTunes) from the menu bar 

### ISSUE THREAD

**Issue by jasenwar** [nbolar/PlayStatus#1]
As title stated

catalina 10.15.2

**Comment by nbolar** [comment]
I just downloaded v1.5 and ran it on Catalina 10.15.2 and it works fine. Do you mind sharing a screen recording of what you're witnessing? Also were you prompted with the following dialog upon opening the app for the first time?
<img width="420" alt="Screen Shot 2020-01-20 at 10 32 53 PM" src="https://user-images.githubusercontent.com/45484873/72773327-cf955f80-3bd4-11ea-85bc-f4b0e131d188.png">

**Comment by nbolar** [comment]
Closing this issue because of no response.
