### ISSUE TITLE
Play/Pause command gets sent to both Spotify and Music?

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#11]
If I have both Spotify and Music open, and I open the PlayStatus dropdown and hit the pause button, the track I'm listening to in Spotify stops and the Music app starts playback. I'm guessing PlayStatus is sending the play/pause command to both apps?

This is easily avoided by simply not having both apps open simultaneously — but I'm guessing it's not the intended behavior, so I wanted to make you aware of it.

**Comment by nbolar** [comment]
Yes, it is a known issue and has been a real pain for a while. The reason that I needed to do this is because there's no way for me to know which of the apps Spotify/Apple Music is the "active" one. I may have a possible fix but it's still slightly finicky. I hope to address this issue soon.

**Comment by dscos** [comment]
I realise that this a super edge usage case — the number of people using the app that also use BOTH Spotify and Music, and happen to have BOTH open at the same time, is probably minimal. So please don't run yourself ragged looking for a fix on my account lol! Thanks so much for all your work on this app!

**Comment by nbolar** [comment]
Okay so I think I've got the fix for this issue. The new version should be live over the weekend. I'll let you know when I've pushed it.

**Comment by nbolar** [comment]
The new version is now live. Let me know if this works for you.

Edit: Build 11 had a bug which build 12 fixed.

**Comment by dscos** [comment]
The issue with play/pause going to both apps is fixed. When both apps are open, the play/pause button works correctly. However, behavior is a little weird with only one app or the other open. If I have only Music open and playing, and hit PlayStatus' pause button, it pauses the music, but also launches Spotify. If I have only Spotify open and playing and hit PlayStatus' pause button, nothing happens.

**Comment by nbolar** [comment]
So that specific issue was fixed with the new build (12) that I pushed last night instead of the build number 11 that went live over the weekend. When you click on check for new updates does it show you any update dialog box?

Edit: If that doesn't work then just delete the app and download the latest build [here.](https://github.com/nbolar/PlayStatus/releases/tag/v2.0.1)

**Comment by nbolar** [comment]
Closing this because I believe the latest update fixed this issue.
