### ISSUE TITLE
Process not responding after wake from sleep.

### ISSUE THREAD

**Issue by okb12** [nbolar/PlayStatus#12]
Sometimes PlayStatus gets stuck with a transparent white rectangle and Activity Monitor shows the process as not responding after waking up from sleep. I generally have spotify paused on the background. Memory usage is ~20Mbytes when the issue occurs.

**Comment by nbolar** [comment]
Hey, thanks for letting me know. That's a strange issue. Let me try replicating it on my end. If I can't replicate it, I may ask you for a little more information.

**Comment by nbolar** [comment]
So unfortunately I haven't been able to replicate this issue. I have a couple of question and would appreciate your feedback:

- Does it happen after each sleep/wake?
- If possible can you attach a screenshot/recording of PlayStatus when it is in that state?

**Comment by okb12** [comment]
Strangely, the issue has never occured again and I am unable to replicate too. I'll reopen if it happens again. Thank you for your time.
