### ISSUE TITLE
Option to ignore parentheticals?

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#14]
Not a bug, just an idea/feature request. I don't use the scrolling option, so I occasionally end up with some super long song titles like in the attached. If there was an option for PlayStatus to ignore parentheticals in song titles, I would use that.
![Screen Shot 2020-11-10 at 11 01 34 AM](https://user-images.githubusercontent.com/14156552/98712887-20cd3600-2344-11eb-8906-d8140bb90c43.jpg)

**Comment by nbolar** [comment]
Hey @dscos! Thanks for your request. I'll play around with that idea and see if I can come up with a solution for it.

**Comment by nbolar** [comment]
I just pushed a new version (2.0.2) that allows you to enable this feature. Let me know what you think of it.

**Comment by dscos** [comment]
Wow. You are the best! Works great.
