### ISSUE TITLE
Is it possible to get currently playing info from Homepods?

### ISSUE THREAD

**Issue by deepcoder** [nbolar/PlayStatus#16]
Great work on this app, thanks.

Wondering it you can, like iTunes, query Homepods or Apple TV?

Thx,

Dave

**Comment by nbolar** [comment]
Hey Dave! Thanks for your feedback. Umm I'm not sure if I can do that but I'll definitely give it a go. Since the app largely works with AppleScript, if I manage to find a workflow that functions well enough, I'll add that. 

I'll keep you posted though.
