### ISSUE TITLE
Hot Keys for Music Controls

### ISSUE THREAD

**Issue by MsQueen** [nbolar/PlayStatus#17]
Is it possible to add universal hot keys for music controls that can be used when any app is active? This is my most missed feature from the once amazing Finely Tuned.

**Comment by nbolar** [comment]
Hi @MsQueen! I'm not acquainted with that app but are the hotkeys different from the default media hotkeys macOS has?

**Comment by MsQueen** [comment]
You actually had the choice to create your own. You could use the default media hotkeys if you wanted.

**Comment by nbolar** [comment]
Ahh okay I see. I might poke around to see how best to implement this feature. I'm unsure how long it will take to complete this but if I do, I'll update this thread. Thanks for your feedback!

**Comment by MsQueen** [comment]
Thanks, keep up the good work!

**Comment by nbolar** [comment]
Hey @MsQueen so I have a beta up and running and it seems to work. Will you be interested in trying/testing it before I release it officially?

**Comment by MsQueen** [comment]
Sorry for the late reply. Gladly!

**Comment by nbolar** [comment]
Here you go. Let me know what you think of it. Thanks!
[PlayStatus.app.zip](https://github.com/nbolar/PlayStatus/files/5743646/PlayStatus.app.zip)

**Comment by MsQueen** [comment]
So far so good. The hot keys work universally and reliably. This feature takes the app that far! Thanks so much.

**Comment by nbolar** [comment]
Awesome! Thanks, I'll push this update out soon.
