### ISSUE TITLE
Hotkeys Extended (Volume)

### ISSUE THREAD

**Issue by MsQueen** [nbolar/PlayStatus#18]
It came to me just after you closed the previous one, but can you add hotkeys for the volume, where you can choose the active volume control to be either from the player (iTunes/Spotify) or the main system volume?

**Comment by nbolar** [comment]
Sure, I could add one set of hotkeys for the player volume and another set for the system volume. Does that sound reasonable to you?

**Comment by MsQueen** [comment]
That works too!

**Comment by nbolar** [comment]
Here's another beta if you'd like to try it
[PlayStatus.app.zip](https://github.com/nbolar/PlayStatus/files/5748970/PlayStatus.app.zip)

**Comment by MsQueen** [comment]
It's perfect!

**Comment by nbolar** [comment]
Great! I'll push out the update in the next few days.
