### ISSUE TITLE
Search Feature to search Apple Music catalog not just library

### ISSUE THREAD

**Issue by derekharmanli** [nbolar/PlayStatus#21]
Is it possible to have the search feature applicable to the whole Apple Music catalog? Currently it is just checking my library (which is empty). Thank you! Amazing app btw.

**Comment by nbolar** [comment]
Thanks for your feedback. Hmm, so the best I could do is when you search for a song using Playstatus, it opens up Apple Music with the results and then you can choose which track to play. Does that sound good?

**Comment by nbolar** [comment]
I've added this feature to version 2.3. Please update the app.
