### ISSUE TITLE
Feature Request: "Menu Bar Title Options" should have an option which only displays the logo of Spotify/iTunes (without title/artist)

### ISSUE THREAD

**Issue by Ein-Tim** [nbolar/PlayStatus#25]
### Feature description

Under "Menu Bar Title Options" the user should have the option to select "Only Display logo".

### Problem and motivation
As song titles and also artist names can get quite long sometimes, PlayStatus is regularly hidden from the menu bar & I can't interact with it. For me personally, it's more important that I always have the possibility to click on the logo in the menu bar and skip/pause the song, than seeing the song title or the artist name.
So I toggle on "Only Display logo" only the logo of either Spotify or iTunes should be shown, just like when no song is playing.

**Comment by nbolar** [comment]
Hi Tim,

Thank you for your feedback. I will look at adding that functionality.

Out of curiosity, have you tried the scrollable text option?

**Comment by Ein-Tim** [comment]
@nbolar 

I appreciate it, thank you very much!

Yes, I have the scrollable text option activated, should this prevent the app icon from getting hidden?

**Comment by nbolar** [comment]
@Ein-Tim 

Technically no, it can still get hidden if you have enough menubar apps. The scrollable title applies to only titles that are over 300 pts long.  Once it is over that limit then the scrollable nature kicks in. However, I understand that 300 pts can be quite long and so it would still get hidden. I might consider lowering that number to maybe 150 to help with this. I'll play around with this idea. 

With that being said I will still add the option of "logo only".

**Comment by Ein-Tim** [comment]
Thank you!

**Comment by nbolar** [comment]
I have a beta up and running. Here's what I've done:

- When scrollable text is selected, I allow the user to specify the length of the scrollable menubar title. By default it is set to 300 pts. You can type any value and hit enter and then restart the app. The new size should come into effect. By playing around with the menubar title options you can get it to exactly how you like.
- I've added in the option to only show the player logo.

Would you like to try it out?

**Comment by Ein-Tim** [comment]
@nbolar 

That sounds great! I'm away from my machine for the next 3 days, but I'd be happy to try it out when I come back on Friday!

**Comment by nbolar** [comment]
@Ein-Tim 

Awesome! I'll hold off from releasing it and wait for your feedback. Let me know once you're back.

Thank you!

**Comment by Ein-Tim** [comment]
@nbolar 

I could now test a new version which includes the changes!

**Comment by nbolar** [comment]
@Ein-Tim 

Here you go. Let me know what you think.

[PlayStatus.zip](https://github.com/nbolar/PlayStatus/files/9585344/PlayStatus.zip)

**Comment by Ein-Tim** [comment]
@nbolar 

Thank you! 

Feedback:
The "Logo only" as well as the individual scrollable text option work great!

**Comment by nbolar** [comment]
Thank you! I'll push the new version in the next couple of days.

**Comment by nbolar** [comment]
Just pushed the update. You should be able to update it within the app. Thank you for your help and feedback!
