### ISSUE TITLE
Doesn't seem to work on ventura

### ISSUE THREAD

**Issue by youzaiooo** [nbolar/PlayStatus#28]
My system is ventura13.2.1. When I open the software, the "Check for updates automatically?" window will pop up. No matter which option I click, it cannot be closed, and the software does not start.

**Comment by nbolar** [comment]
What happens when you force close the app and reopen it? I'm running macOS Ventura 13.2.1 as well.

**Comment by youzaiooo** [comment]
Then it just shuts down..Later, I started the program again, and there was no response anymore, but the system had its processes running.

**Comment by youzaiooo** [comment]
One more thing, I'm macosX

**Comment by nbolar** [comment]
After you launch the application for the second time, in your menu bar you should see the app running. It should look like a music icon.

**Comment by youzaiooo** [comment]
Oh..I see it,It turned out to be hidden by bartender4(°᷄д°᷅)..Thanks
