### ISSUE TITLE
Feature Request: Hotkey on Search Function

### ISSUE THREAD

**Issue by MsQueen** [nbolar/PlayStatus#29]
Is there anyway you could implement a hotkey that makes the menu app appear with the search text box active?

**Comment by nbolar** [comment]
As it stand right now, if PlayStatus is active i.e. the player view is in focus, you can hit the "S" key and it will present you with the active search text box. This only works if you use the Music app. It does not support Spotify

**Comment by MsQueen** [comment]
Cool, can we get the capability to focus the player from anywhere in the OS with a hotkey? But if not, the S on focus is one less of a click and I'll take it.

**Comment by nbolar** [comment]
Okay so I implemented a global search hotkey, just like you requested in your first comment. It makes the app appear with the search text box active. You can try out the beta that I've attached here. Let me know what you think.
[PlayStatus.zip](https://github.com/nbolar/PlayStatus/files/10997336/PlayStatus.zip)

**Comment by MsQueen** [comment]
Amazing! It works well. I appreciate your promptness commenting and taking action. 
Btw, there's an extra space between <Search and Key> in the Hot Keys preference tab, just in case you haven't caught it yet. Keep up the great work!

**Comment by nbolar** [comment]
So I finally got around to pushing the update... 2 months later, haha. Closing this issue.
