### ISSUE TITLE
Setting to toggle app icon?

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#3]
Do you have any plans to add a setting to toggle the PlayStatus icon in the menubar? Would prefer a cleaner look or the Music/Spotify icons instead. I'd be willing to donate something for you to do this lol.

**Comment by nbolar** [comment]
Hmm I could sort of use multiple icons and switch between the Music and Spotify icons depending on which app is playing the music. I'll add that into the next version!
