### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by gadddy** [nbolar/PlayStatus#30]
Hey, I was just wondering if some customisation could be performed on the player. For example, different preset widths so that the player doesn't overflow for songs with longer titles. Thank you!

**Comment by nbolar** [comment]
@gadddy As it stands right now, you can choose the scrollable text title option. Any long titles greater than 300pts, it begins scrolling it. You can choose at what point it scrolls. The default is 300, but you can make it shorter. Have you tried that option?
