### ISSUE TITLE
Song metadata doesnt change when changing tracks in icon only mode. 

### ISSUE THREAD

**Issue by FrozenBrick** [nbolar/PlayStatus#32]
Hey, love the app. Just a minor issue i noticed. When i set it to icon only mode and try to change to track, info doesnt get updated but the song plays. 

https://github.com/nbolar/PlayStatus/assets/19780503/3e03a140-ac01-482e-818d-860fc8ea06f4

**Comment by nbolar** [comment]
Hey @FrozenBrick! Thank you for reaching out. This definitely is a bug. Let me dig into this.

**Comment by nbolar** [comment]
@FrozenBrick I have a build with this fix. Would you be willing to test it out?

**Comment by FrozenBrick** [comment]
@nbolar Yeah sure. Happy to test it out.

**Comment by nbolar** [comment]
Here you go:

[PlayStatus.zip](https://github.com/nbolar/PlayStatus/files/12859720/PlayStatus.zip)


Just make sure the other version is not running.

**Comment by FrozenBrick** [comment]
Its keeps crashing when i try to change a song or try to interact with it. Regardless of which settings i apply. I did remove the old one completely. 

The old one still works, like doesnt crash.

**Comment by nbolar** [comment]
Do you mind sharing a video of it, please?

**Comment by FrozenBrick** [comment]
Notice how it only crash when i interact with it while a song is playing .


https://github.com/nbolar/PlayStatus/assets/19780503/a4b86cf1-553a-45b3-9823-287dfbdc00e3

**Comment by nbolar** [comment]
Hmm... I'm unable to replicate this, but I made some other changes. I'll try debugging it but for now here is an updated release:
[PlayStatus.zip](https://github.com/nbolar/PlayStatus/files/12871473/PlayStatus.zip)

**Comment by nbolar** [comment]
@FrozenBrick Just wanted to know if the newest beta worked for you?

**Comment by FrozenBrick** [comment]
No, it did not. What all permission does it need? I was thinking of manually adding in the settings

**Comment by nbolar** [comment]
It uses the following settings:
<img width="499" alt="image" src="https://github.com/nbolar/PlayStatus/assets/45484873/60c12814-9fd1-489c-bd9b-a0c57e3d1ae4">

<img width="499" alt="image" src="https://github.com/nbolar/PlayStatus/assets/45484873/12dd1cba-31f0-49c7-b724-77e7c04a6be8">


I tried installing it on a new laptop and also as different user and I was not able to replicate the crash.

**Comment by FrozenBrick** [comment]
I think its me doing something. How do i probably remove it. Even after using App Unistallers, there seems to something left. Like i open the app again and settings are exactly how i left it.

**Comment by FrozenBrick** [comment]
I will just reset my mac and try again.

**Comment by nbolar** [comment]
I would just drag and drop all the downloaded copies of the app into the trash and then empty the trash.

**Comment by FrozenBrick** [comment]
yup working fine on other mac. Bug fixeddd.
