### ISSUE TITLE
Disappears after launch?!

### ISSUE THREAD

**Issue by the-maty** [nbolar/PlayStatus#35]
Hey, installed app and after launch it appears in menu bar but disappears after a sec. In activity monitor its running, but its not in menu bar. 
It didn't ask me after install for any permissions. Can this be the problem?

**Comment by the-maty** [comment]
After quick click before its gone :D I ticked option "Ignore Parentheticals in song names" that seems to work now. Scrollable text broke it too, when I tried to enable it 😕 
EDIT: Now its gone again :D

**Comment by nbolar** [comment]
Hmmm, I'm not sure I follow. I tried to replicate what you mentioned but it seems to be working fine on my end. Can you try quitting the app via activity monitor and relaunching it?

**Comment by the-maty** [comment]
That is the first thing I did. Same problem after quiting in activity monitor.

**Comment by nbolar** [comment]
If it's active in Activity Monitor then it should be present on the menubar. Can you please share a screenshot or video of the issue?

**Comment by the-maty** [comment]
Okay, I am not at home right now. I will send it as soon as possible.

**Comment by the-maty** [comment]
right after start, it appears and its gone. 
<img width="923" alt="Snímek obrazovky 2023-12-29 v 21 26 27" src="https://github.com/nbolar/PlayStatus/assets/52372122/257fe534-6fba-4baf-9f1c-9269bc23bfdd">

Activity monitor 
<img width="923" alt="Snímek obrazovky 2023-12-29 v 21 27 34" src="https://github.com/nbolar/PlayStatus/assets/52372122/245a47bf-3350-4e33-981f-c6a7c2f229e3">

**Comment by the-maty** [comment]
There is a video 
https://streamable.com/rjwmud

**Comment by nbolar** [comment]
It looks like you might be using a menubar app like bartender or iStats or something similar that hides certain apps from the menubar. Can you please check to see if that is the case?

**Comment by the-maty** [comment]
Only things I use are TG Pro, https://github.com/exelban/stats , OneMenu and AlDante. Dont have bartender or iStats installed.
Tried to disable OneMenu and stats. Still dissapears

**Comment by the-maty** [comment]
Maybe I can try clean install the app? Can you guide me what to delete to perform clean install?

**Comment by nbolar** [comment]
Drag the app to the trash and then delete it from trash. Then go to ~/Library/Preferences/ and delete com.bolar.PlayStatus.plist

**Comment by the-maty** [comment]
Done, should I install the latest?

**Comment by nbolar** [comment]
Yes please

**Comment by the-maty** [comment]
Opened, clicked "open" was a sec in menubar then its gone. Same problem

**Comment by nbolar** [comment]
That is very strange.... Can you go to System Preferences > Privacy & Security > Accessibility and see if PlayStatus is listed?

**Comment by the-maty** [comment]
Found a new thing, when I force close spotify the playstatus spawnes in menubar. When I click play, its gone again.

**Comment by the-maty** [comment]
> That is very strange.... Can you go to System Preferences > Privacy & Security > Accessibility and see if PlayStatus is listed?
<img width="521" alt="Snímek obrazovky 2023-12-29 v 21 56 09" src="https://github.com/nbolar/PlayStatus/assets/52372122/53c76c82-698c-47c2-a85e-6ecc3695afac">
Yep, its here

**Comment by nbolar** [comment]
Just out of curiosity can you share the song/playlist you are using on Spotify? I'm trying to see if it's something with the length...

**Comment by the-maty** [comment]
> Just out of curiosity can you share the song/playlist you are using on Spotify? I'm trying to see if it's something with the length...

https://open.spotify.com/playlist/37i9dQZF1E8SQg5Ghrjbkt?si=01dfbf5544814438

**Comment by the-maty** [comment]
I tried to capture it https://streamable.com/9pq1ko

**Comment by nbolar** [comment]
Okay I think I might know what's happening. Do you happen to have the latest MacBook with the notch?

**Comment by the-maty** [comment]
> Okay I think I might know what's happening. Do you happen to have the latest MacBook with the notch?

Yes sir I do
14" Macbook Pro

**Comment by nbolar** [comment]
Ahh okay the thing is if the length of the text is too big to fit in the menubar  along with all the other apps in the menubar then it seems to hide it. There are a few things you can do, please bare with me:

1. Can you choose icon only option in the Playstatus settings and then play the song? If that icon remains there, then try to choose artist only or song only options to verify what I said above.
2. What you can do is, choose the scrollable title option, and then enter a value in the text box that is less than 300, for example 100 or 50, just to try.

**Comment by the-maty** [comment]
> Ahh okay the thing is if the length of the text is too big to fit in the menubar along with all the other apps in the menubar then it seems to hide it. There are a few things you can do, please bare with me:
> 
> 1. Can you choose icon only option in the Playstatus settings and then play the song? If that icon remains there, then try to choose artist only or song only options to verify what I said above.
> 2. What you can do is, choose the scrollable title option, and then enter a value in the text box that is less than 300, for example 100 or 50, just to try.

Ok, going to try

**Comment by the-maty** [comment]
Artist only works fine 👍 , going to try that 2. option

**Comment by nbolar** [comment]
Just be sure to hit the enter/return key after specifying a value.

**Comment by the-maty** [comment]
Did artist name and song title
Limited to 100 restarted and works fine 👍

**Comment by nbolar** [comment]
Awesome, so without the scrollable option, if the title of the music you're playing is too long, then it will just hide it. Unfortunately there's nothing I can do there because it is more of a macOS issue than PlayStatus.

**Comment by the-maty** [comment]
yes thats correct, tried some long song and it just hides when I dont use scrollable option. Thats a shame

**Comment by nbolar** [comment]
Yes, I agree. The only other option is to increase the display resolution to the "more space" option but even then it does not guarantee that all long song titles will show up 😞

**Comment by the-maty** [comment]
> Yes, I agree. The only other option is to increase the display resolution to the "more space" option but even then it does not guarantee that all long song titles will show up 😞

I guess that for now I am gonna disable some things in menubar and find sweet spot

**Comment by nbolar** [comment]
Sounds good! Thank you so much for working with me through this issue! 🙂

**Comment by the-maty** [comment]
> Sounds good! Thank you so much for working with me through this issue! 🙂

I thank you, I was so confused why its gone :D
