### ISSUE TITLE
Horizontal padding

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#4]
Is it possible to either add horizontal padding or add an option for it? The artist/song text bumps right up the next icon in my menubar.

**Comment by nbolar** [comment]
Done! I added a slight right padding and will push a new version soon. I'll update this thread as soon as I push the update.

**Comment by dscos** [comment]
🙌

**Comment by nbolar** [comment]
Just pushed v1.7. You should be able to update from within the app now. Let me know of any issues.

**Comment by dscos** [comment]
Nice, thanks!
