### ISSUE TITLE
Focusing another app doesn't dismiss PlayStatus dropdown

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#5]
I don't know if this was present before 1.8 or not, but I don't think it was. If you click the PlayStatus area to summon the controls/album art dropdown and then click away to focus another app, the PlayStatus dropdown stays on top. Not a big deal, clicking on the PlayStatus area again does dismiss the dropdown, but just thought I'd let you know.

**Comment by nbolar** [comment]
That was a bug from the very start and I never got around to fixing it. You've been a pretty good beta tester haha! I've just pushed v1.8.1 that should now work better. Let me know if it doesn't.

**Comment by dscos** [comment]
Yep, that fixed it!
