### ISSUE TITLE
Tooltip sometimes gets "stuck"

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#6]
Have you noticed the tooltip sometimes getting "stuck" or appearing where it shouldn't? For example, I've noticed on several occasions the tooltip just appearing (seemingly randomly) about an inch or so below where you would expect to see it, on top of my Safari window. It's not a big deal, since hovering over the PlayStatus area in the menubar makes it go away, but I thought I would bring it to your attention. I'll try to grab a screenshot the next time it happens.

**Comment by nbolar** [comment]
Yeah I noticed that and decided to remove the feature because it was kind of pointless anyway. I just pushed an update and it should be live now.
