### ISSUE TITLE
Memory issue?

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#7]
PlayStatus is using 1.15 GB of RAM on my machine right now. I have 16GB RAM so it's not a big deal for me, but it seems excessive for a menubar app so I thought I'd bring it to your attention.

![Screen Shot 2020-03-20 at 5 12 06 PM](https://user-images.githubusercontent.com/14156552/77212877-6778d200-6ace-11ea-81c3-c02cb8777791.jpg)

**Comment by nbolar** [comment]
Okay that definitely is concerning. Let me see what the issue is and I'll get back to you.

Edit: Just a quick side note till I find the issue, what happens when you restart the app and then track it using Activity Monitor?

**Comment by dscos** [comment]
Sorry, just saw this. Closed the app and relaunched it, it started at 7.5 MB and then jumped to around 11 MB. After about 15 minutes it's at 18.1 MB now. A few times, it seemed to jump up by 3-4 MB when I skipped tracks, but that doesn't seem to be happening. I'll continue to check it and update.

**Comment by dscos** [comment]
After about an hour it's at 50.4 MB

**Comment by nbolar** [comment]
I've been trying to figure out what's causing this for the past few days and it looks like the scrolling menu bar feature of the app is the culprit i.e. when song names are large and require the scrollable feature, there is a slow but steady increase in memory. On the other hand if I disable the scrolling ability, the memory consumption stays relatively constant and significantly lower. Unfortunately that bit was not coded by me and is a third party open source file that I've incorporated. So as of now, I'm not sure how far I'll be able to optimize it. But I'll keep working on it.

**Comment by dscos** [comment]
Personally, I liked the old SpotMenu behavior of not scrolling and just displaying the whole long song title, but I'm probably in the minority on that. Maybe make it a toggleable option with a note that the scrolling functionality eats more memory? Or is there maybe a middle ground where you could make the PlayStatus area wider, thus necessitating scrolling less frequently?

Like I said, I have plenty of memory so it's not a big deal for me personally, and now that I'm aware, I can always restart the app if it gets out of hand.

**Comment by nbolar** [comment]
You make some good points. I'll consider adding those preferences so that the user can choose what they want, into the next update. It'll probably take some time to finalize the next version just so that I make sure that the different options don't eat up too much memory.

**Comment by nbolar** [comment]
Hey @dscos the new update is now live. Hopefully this fixes the memory usage bug. Also hope the Spotify bug gets fixed soon.
