### ISSUE TITLE
Allow configuring a default music app

### ISSUE THREAD

**Issue by raisedadead** [nbolar/PlayStatus#8]
When I do not have a music app open, and click on the PlayStatus (ex. Play, Music Icon, etc.) it opens Apple Music by default. Since I Prefer Spotify to be the player of choice, I would love it were configurable in a settings page or something.

**Comment by nbolar** [comment]
Hey, thanks for your feedback. That has crossed my mind and I do plan on providing the option of a default player with the next update. It might be some time from now though as I'm currently working through some other issues. I'll be sure to update this thread as soon as the new version is live.

**Comment by raisedadead** [comment]
Sure, happy to be a tester before you release.

**Comment by nbolar** [comment]
Hey @raisedadead so I have a beta that I'd love to get your feedback on. There are quite a few changes I've been working on. There's a new settings page that'll give you some customizability. I've added in a default player option too. Let me know your thoughts.

- [PlayStatus.app.zip](https://github.com/nbolar/PlayStatus/files/4519272/PlayStatus.app.zip)

**Comment by raisedadead** [comment]
Thanks for the update. This looks and works great. Thanks for your hard work :)

Some nitpicks (don't even bother working this unless someone really complains):

1. The app seems to be using a Apple music like background when nothing is playing? 

![image](https://user-images.githubusercontent.com/1884376/80047510-3e16f000-852b-11ea-8fde-f41c438e661b.png)

2. The icon for thr player (Spotify/Apple music) seems to be syncing only in between restarts for the app. i.e. I have to exit the app and launch it again?

Note: The functionality itself works and the correct music app is set and used as default.

![image](https://user-images.githubusercontent.com/1884376/80047664-ac5bb280-852b-11ea-986c-a35eaf6f63ca.png)

**Comment by nbolar** [comment]
Thank you very much for your feedback!

1. Yeah about that I haven't really known what background to set when no music is playing. I might just add in a clear background with some text along the lines of no music playing.

2. Okay good catch, I'll be sure to fix that for the official release.

I'll be sure to update this thread when I push the official update which may be sometime by the end of this week. Thanks once again!

**Comment by nbolar** [comment]
The new update is now live with all the changes and a few tweaks that you recommended! Thank you very much once again!

**Comment by raisedadead** [comment]
I just updated it and tested everything. Works like a charm, I tested the default player setting, icons, its looks neat now.

Thanks again, have a good one.
