### ISSUE TITLE
error when trying to build

### ISSUE THREAD

**Issue by xrisk** [nbolar/PlayStatus#9]
I’m trying to build the project from source but I get 
```
/Users/xrisk/dev/PlayStatus/Pods/Target Support Files/Pods-PlayStatus/Pods-PlayStatus.debug.xcconfig: unable to open file (in target "PlayStatus" in project "PlayStatus”)
```

What do I do to fix this?

**Comment by nbolar** [comment]
Okay so it looks like the podfile is missing, which is an error on my end while committing my code. I'll make sure to include the podfile when the next version goes live. In order to get it to work, you need to manually create a podfile with the following cocoa pods:
```
pod 'CircularProgressMac'
pod 'LoginServiceKit', :git => 'https://github.com/Clipy/LoginServiceKit.git'
pod 'Sparkle'
```
After doing that, you'll be able to work off the newly created xcworkspace file. Let me know if you have anymore questions.

**Comment by xrisk** [comment]
Ok so, I did that and now I have a fresh error:

```
error: Build input file cannot be found: '/Users/xrisk/dev/GitHub/SpotMenu/SpotMenu/CustomViews/ScrollingTextView.swift' (in target 'PlayStatus' from project 'PlayStatus’)
```

It seems some kind of path is hardcoded, because I don’t have any `GitHub` directory.

This seems to be the problem:

<img width="259" alt="Screen Shot 2020-04-12 at 8 48 55 AM" src="https://user-images.githubusercontent.com/10669859/79059678-81a36b80-7c9a-11ea-9585-e131a3c3bca9.png">


---

For reference, here is the Podfile I created:
```
target 'PlayStatus' do
    pod 'CircularProgressMac'
    pod 'LoginServiceKit', :git => 'https://github.com/Clipy/LoginServiceKit.git'
    pod 'Sparkle'
end
```

followed by `pod install` and then I opened `PlayStatus.xcworkspace` in Xcode.

**Comment by nbolar** [comment]
Thanks for letting me know. Here's the fix for it: First copy all the code in the ScrollingTextView.swift file and delete the file completely and create a new swift file titled the same and paste the code back in it and then build the project. That should work.
